---
version: '3.7'

services:
  app:
    image: registry.gitlab.com/mlaplanche/personal-website:latest
    restart: always
    environment:
      - "VIRTUAL_HOST=maxime-laplanche.web4me.fr,maxime-laplanche.fr,www.maxime-laplanche.fr"
      - "LETSENCRYPT_HOST=maxime-laplanche.web4me.fr,maxime-laplanche.fr,www.maxime-laplanche.fr"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mltechapp.rule=Host(`maxime-laplanche.fr`)"
      - "traefik.http.middlewares.mltechappheaders.headers.accessControlMaxAge=604800"

    networks:
      - server_stack_traefik
      - default-network
    tty: true
    container_name: personal-website

networks:
  default-network:
  server_stack_traefik:
    external: true
